### ISSUE TITLE
No module named PIL

### ISSUE THREAD

**Issue by Alphonsso** [mblack1/TextbookScreenshotter#1]
Hi,

I'm not very familiar with using python, but I think I've followed everything.

I am using python 3.9 and have ensured that Pillow and pyautogui are installed, I then ran the script through CMD as:
`D:\Desktop\Screenshot>screenshot.py`
and it returns with:
```
D:\Desktop\Screenshot>screenshot.py
Traceback (most recent call last):
  File "D:\Desktop\Screenshot\screenshot.py", line 1, in <module>
    from PIL import Image, ImageGrab
ModuleNotFoundError: No module named 'PIL'
```
I've tried changed the script to point towards Pillow:
`from Pillow import Image, ImageGrab `
and it does the same thing:
```
D:\Desktop\Screenshot>screenshot.py
Traceback (most recent call last):
  File "D:\Desktop\Screenshot\screenshot.py", line 1, in <module>
    from Pillow import Image, ImageGrab
ModuleNotFoundError: No module named 'Pillow'
```

Anything that I'm doing wrong?

**Comment by Alphonsso** [comment]
Uninstalling, restarting, reinstalling, restarting, installing modules and restarting again has resolved this issue.
